using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dil.Generator
{
    /// <summary>
    /// Generates a strongly-typed <c>Resources</c> class from the project's
    /// default <c>l.json</c> file (added as an <c>AdditionalFiles</c> item).
    /// Each JSON key becomes a property; values with <c>{token}</c> placeholders
    /// become methods with one parameter per token.
    /// </summary>
    [Generator]
    public sealed class LocalizationGenerator : IIncrementalGenerator
    {
        private static readonly Regex PlaceholderRegex = new Regex(@"\{(\w+)\}", RegexOptions.Compiled);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var keyFile = context.AdditionalTextsProvider
                .Where(static f => string.Equals(
                    System.IO.Path.GetFileName(f.Path), "l.json", StringComparison.OrdinalIgnoreCase))
                .Collect();

            var rootNamespace = context.AnalyzerConfigOptionsProvider.Select(static (p, _) =>
                p.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns)
                && !string.IsNullOrWhiteSpace(ns)
                    ? ns
                    : "Dil");

            var combined = keyFile.Combine(rootNamespace);

            context.RegisterSourceOutput(combined, static (spc, pair) =>
            {
                var (files, ns) = pair;
                if (files.IsDefaultOrEmpty) return;

                var text = files[0].GetText(spc.CancellationToken)?.ToString() ?? string.Empty;
                var entries = FlatJson.Parse(text);
                var source = Emit(ns, "Resources", entries);
                spc.AddSource("Dil.Resources.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        private static string Emit(string ns, string className, List<KeyValuePair<string, string>> entries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace " + ns);
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Strongly-typed localized strings, generated by Dil from l.json.</summary>");
            sb.AppendLine("    public static partial class " + className);
            sb.AppendLine("    {");

            var used = new HashSet<string>(StringComparer.Ordinal);
            foreach (var kv in entries)
            {
                var member = ToPascal(kv.Key);
                if (member.Length == 0) continue;

                var baseName = member;
                var n = 2;
                while (!used.Add(member)) member = baseName + n++;

                var keyLiteral = Literal(kv.Key);
                var placeholders = ExtractPlaceholders(kv.Value);

                sb.AppendLine("        /// <summary>" + EscapeXml(kv.Value) + "</summary>");
                if (placeholders.Count == 0)
                {
                    sb.AppendLine("        public static string " + member +
                                  " => global::Dil.Loc.Get(" + keyLiteral + ");");
                }
                else
                {
                    var pars = string.Join(", ", placeholders.Select(p => "object? " + p));
                    var args = string.Join(", ", placeholders.Select(p => "(" + Literal(p) + ", " + p + ")"));
                    sb.AppendLine("        public static string " + member + "(" + pars + ")" +
                                  " => global::Dil.Loc.Format(" + keyLiteral + ", " + args + ");");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static List<string> ExtractPlaceholders(string value)
        {
            var list = new List<string>();
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (Match m in PlaceholderRegex.Matches(value))
            {
                var name = m.Groups[1].Value;
                if (name.Length == 0 || char.IsDigit(name[0])) continue; // skip {0}-style
                var ident = EscapeKeyword(name);
                if (seen.Add(ident)) list.Add(ident);
            }
            return list;
        }

        private static string ToPascal(string key)
        {
            var sb = new StringBuilder();
            var upper = true;
            foreach (var c in key)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(upper ? char.ToUpperInvariant(c) : c);
                    upper = false;
                }
                else upper = true;
            }
            var s = sb.ToString();
            if (s.Length > 0 && char.IsDigit(s[0])) s = "_" + s;
            return s;
        }

        private static string EscapeKeyword(string ident) =>
            CsharpKeywords.Contains(ident) ? "@" + ident : ident;

        private static string Literal(string s) =>
            "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"")
                    .Replace("\r", "\\r").Replace("\n", "\\n") + "\"";

        private static string EscapeXml(string s) =>
            s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
             .Replace("\r", " ").Replace("\n", " ");

        private static readonly HashSet<string> CsharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
            "continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern",
            "false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface",
            "internal","is","lock","long","namespace","new","null","object","operator","out","override","params",
            "private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc",
            "static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked",
            "unsafe","ushort","using","virtual","void","volatile","while"
        };
    }
}
