//HintName: Dil.Errors.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Errors
    {
        Errors() { }

        static Errors()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Errors", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Errors.json"),
            });
        }

        /// <summary>Invalid credentials</summary>
        public static string Login_InvalidCredentials => global::Dil.Loc.Get("DilGeneratorTests/Errors", "Login_InvalidCredentials");
    }
}
