//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("Strings", key, args);

        /// <summary>Hi {name}</summary>
        public static GreetingTemplate2 Greeting => default;
        /// <summary>The <c>greeting</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct GreetingTemplate2
        {
            /// <inheritdoc cref="global::MyApp.Strings.Greeting"/>
            public string Template => global::MyApp.Strings.__Get("greeting");
            /// <inheritdoc cref="global::MyApp.Strings.Greeting"/>
            public string Render<T1>(T1 name) => global::MyApp.Strings.__Format("greeting", ("name", name));
        }
        /// <summary>plain</summary>
        public static string GreetingTemplate => global::Dil.Loc.Get("Strings", "greetingTemplate");
        /// <summary>{x}</summary>
        public static RenderTemplate Render => default;
        /// <summary>The <c>render</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct RenderTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Render"/>
            public string Template => global::MyApp.Strings.__Get("render");
            /// <inheritdoc cref="global::MyApp.Strings.Render"/>
            public string Render<T1>(T1 x) => global::MyApp.Strings.__Format("render", ("x", x));
        }
        /// <summary>{y}</summary>
        public static TemplateTemplate Template => default;
        /// <summary>The <c>template</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct TemplateTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Template"/>
            public string Template => global::MyApp.Strings.__Get("template");
            /// <inheritdoc cref="global::MyApp.Strings.Template"/>
            public string Render<T1>(T1 y) => global::MyApp.Strings.__Format("template", ("y", y));
        }
        /// <summary>{Strings} {Template} {__Format} {T1}</summary>
        public static ShadowTemplate Shadow => default;
        /// <summary>The <c>shadow</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct ShadowTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Shadow"/>
            public string Template => global::MyApp.Strings.__Get("shadow");
            /// <inheritdoc cref="global::MyApp.Strings.Shadow"/>
            public string Render<T2, T3, T4, T5>(T2 Strings, T3 Template, T4 __Format, T5 T1) => global::MyApp.Strings.__Format("shadow", ("Strings", Strings), ("Template", Template), ("__Format", __Format), ("T1", T1));
        }
    }
}
