//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace InsuranceUp.Modules.AgentUserManagement.Application.Resources
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/AgentUserManagement/Strings.json"),
                ("tr", "Dil/DilGeneratorTests/AgentUserManagement/Strings.tr.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("DilGeneratorTests/Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("DilGeneratorTests/Strings", key, args);

        /// <summary>Hello, {name}!</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>tr</c>: Merhaba, {name}!</item>
        /// </list>
        /// </remarks>
        public static HelloTemplate Hello => default;
        /// <summary>The <c>hello</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct HelloTemplate
        {
            /// <inheritdoc cref="global::InsuranceUp.Modules.AgentUserManagement.Application.Resources.Strings.Hello"/>
            public string Template => global::InsuranceUp.Modules.AgentUserManagement.Application.Resources.Strings.__Get("hello");
            /// <inheritdoc cref="global::InsuranceUp.Modules.AgentUserManagement.Application.Resources.Strings.Hello"/>
            public string Render<T1>(T1 name) => global::InsuranceUp.Modules.AgentUserManagement.Application.Resources.Strings.__Format("hello", ("name", name));
        }
    }
}
