//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Strings.json"),
            });
        }

        /// <summary>A</summary>
        public static string A => global::Dil.Loc.Get("DilGeneratorTests/Strings", "a");
        /// <summary>B</summary>
        public static string B => global::Dil.Loc.Get("DilGeneratorTests/Strings", "b");
    }
}
