//HintName: Dil.OrderNew.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class OrderNew
    {
        OrderNew() { }

        static OrderNew()
        {
            global::Dil.Loc.Register("DilGeneratorTests/OrderNew", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Order.New.json"),
            });
        }

        /// <summary>OK</summary>
        public static string Ok => global::Dil.Loc.Get("DilGeneratorTests/OrderNew", "ok");
    }
}
