//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp.Localization.Resources
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Localization/Resources/Strings.json"),
                ("tr", "Dil/DilGeneratorTests/Localization/Resources/Strings.tr.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("DilGeneratorTests/Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("DilGeneratorTests/Strings", key, args);

        /// <summary>Hello, {name}!</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>tr</c>: Merhaba, {name}!</item>
        /// </list>
        /// </remarks>
        public static GreetingTemplate Greeting => default;
        /// <summary>The <c>greeting</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct GreetingTemplate
        {
            /// <inheritdoc cref="global::MyApp.Localization.Resources.Strings.Greeting"/>
            public string Template => global::MyApp.Localization.Resources.Strings.__Get("greeting");
            /// <inheritdoc cref="global::MyApp.Localization.Resources.Strings.Greeting"/>
            public string Render<T1>(T1 name) => global::MyApp.Localization.Resources.Strings.__Format("greeting", ("name", name));
        }
    }
}
