//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Strings.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("DilGeneratorTests/Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("DilGeneratorTests/Strings", key, args);

        /// <summary>hi {x:int; evil()}</summary>
        public static MTemplate M => default;
        /// <summary>The <c>m</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct MTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.M"/>
            public string Template => global::MyApp.Strings.__Get("m");
            /// <inheritdoc cref="global::MyApp.Strings.M"/>
            public string Render<T1>(T1 x) => global::MyApp.Strings.__Format("m", ("x", x));
        }
    }
}
