//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    public sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
            });
        }

        /// <summary>Hello, {name:string}!</summary>
        public static string Greet(string name) => global::Dil.Loc.Format("Strings", "greet", ("name", name));
        /// <summary>{a:int} then {b}</summary>
        public static string Mix<T1>(int a, T1 b) => global::Dil.Loc.Format("Strings", "mix", ("a", a), ("b", b));
    }
}
