//HintName: Dil.Odd.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp.My_Folder._2nd.Level.@class
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Odd
    {
        Odd() { }

        static Odd()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Odd", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/My Folder/2nd.Level/class/Odd.json"),
            });
        }

        /// <summary>Note</summary>
        public static string Note => global::Dil.Loc.Get("DilGeneratorTests/Odd", "note");
    }
}
