//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Strings.json"),
                ("tr", "Dil/DilGeneratorTests/Strings.tr.json"),
            });
        }

        /// <summary>Cancel</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>tr</c>: İptal</item>
        /// </list>
        /// </remarks>
        public static string CommonCancel => global::Dil.Loc.Get("DilGeneratorTests/Strings", "Common_Cancel");
    }
}
