//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Strings.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("DilGeneratorTests/Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("DilGeneratorTests/Strings", key, args);

        /// <summary>First</summary>
        public static string UserFirstName => global::Dil.Loc.Get("DilGeneratorTests/Strings", "user.first-name");
        /// <summary>Save</summary>
        public static string SaveChanges => global::Dil.Loc.Get("DilGeneratorTests/Strings", "save_changes");
        /// <summary>1</summary>
        public static string FooBar => global::Dil.Loc.Get("DilGeneratorTests/Strings", "foo-bar");
        /// <summary>2</summary>
        public static string FooBar2 => global::Dil.Loc.Get("DilGeneratorTests/Strings", "foo.bar");
        /// <summary>first</summary>
        public static string _1st => global::Dil.Loc.Get("DilGeneratorTests/Strings", "1st");
        /// <summary>in {class} for {event}</summary>
        public static MsgTemplate Msg => default;
        /// <summary>The <c>msg</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct MsgTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Msg"/>
            public string Template => global::MyApp.Strings.__Get("msg");
            /// <inheritdoc cref="global::MyApp.Strings.Msg"/>
            public string Render<T1, T2>(T1 @class, T2 @event) => global::MyApp.Strings.__Format("msg", ("class", @class), ("event", @event));
        }
        /// <summary>{x} and {x}</summary>
        public static DupTemplate Dup => default;
        /// <summary>The <c>dup</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct DupTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Dup"/>
            public string Template => global::MyApp.Strings.__Get("dup");
            /// <inheritdoc cref="global::MyApp.Strings.Dup"/>
            public string Render<T1>(T1 x) => global::MyApp.Strings.__Format("dup", ("x", x));
        }
    }
}
