//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
                ("en", "Strings.en.json"),
            }, "en-US");
        }

        /// <summary>Hello</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>en</c>: Hello</item>
        /// </list>
        /// </remarks>
        public static string Hello => global::Dil.Loc.Get("Strings", "hello");
        /// <summary>Bye (neutral)</summary>
        public static string Bye => global::Dil.Loc.Get("Strings", "bye");
    }
}
