//HintName: Dil.User.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class User
    {
        User() { }

        static User()
        {
            global::Dil.Loc.Register("User", new (string, string)[]
            {
                ("", "User.json"),
            });
        }

        /// <summary>Id</summary>
        public static string Id => global::Dil.Loc.Get("User", "id");
    }
}
