//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    public sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
            });
        }

        /// <summary>First</summary>
        public static string UserFirstName => global::Dil.Loc.Get("Strings", "user.first-name");
        /// <summary>Save</summary>
        public static string SaveChanges => global::Dil.Loc.Get("Strings", "save_changes");
        /// <summary>1</summary>
        public static string FooBar => global::Dil.Loc.Get("Strings", "foo-bar");
        /// <summary>2</summary>
        public static string FooBar2 => global::Dil.Loc.Get("Strings", "foo.bar");
        /// <summary>first</summary>
        public static string _1st => global::Dil.Loc.Get("Strings", "1st");
        /// <summary>in {class} for {event}</summary>
        public static string Msg<T1, T2>(T1 @class, T2 @event) => global::Dil.Loc.Format("Strings", "msg", ("class", @class), ("event", @event));
        /// <summary>{x} and {x}</summary>
        public static string Dup<T1>(T1 x) => global::Dil.Loc.Format("Strings", "dup", ("x", x));
    }
}
