//HintName: Dil.Customer.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Customer
    {
        Customer() { }

        static Customer()
        {
            global::Dil.Loc.Register("Customer", new (string, string)[]
            {
                ("", "Customer.json"),
                ("tr", "Customer.tr.json"),
            });
        }

        /// <summary>Name</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>tr</c>: Ad</item>
        /// </list>
        /// </remarks>
        public static string Name => global::Dil.Loc.Get("Customer", "name");
        /// <summary>Email</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>tr</c>: E-posta</item>
        /// </list>
        /// </remarks>
        public static string Email => global::Dil.Loc.Get("Customer", "email");
    }
}
