//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    public sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
                ("de", "Strings.de.json"),
            });
        }

        /// <summary>Hello</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>de</c>: Hallo</item>
        /// </list>
        /// </remarks>
        public static string Hello => global::Dil.Loc.Get("Strings", "hello");
        /// <summary>Hello, {name}!</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>de</c>: Hallo, {name}!</item>
        /// </list>
        /// </remarks>
        public static string Greeting<T1>(T1 name) => global::Dil.Loc.Format("Strings", "greeting", ("name", name));
        /// <summary>You have {count} unread messages</summary>
        public static string Inbox<T1>(T1 count) => global::Dil.Loc.Format("Strings", "inbox", ("count", count));
    }
}
