//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    public sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
            });
        }

        /// <summary>all</summary>
        public static string Strings2 => global::Dil.Loc.Get("Strings", "strings");
        /// <summary>Hello</summary>
        public static string Hello => global::Dil.Loc.Get("Strings", "hello");
    }
}
