//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
            });
        }

        /// <summary>hi {x:int; evil()}</summary>
        public static string M<T1>(T1 x) => global::Dil.Loc.Format("Strings", "m", ("x", x));
    }
}
