//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Strings.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("DilGeneratorTests/Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("DilGeneratorTests/Strings", key, args);

        /// <summary>Hello, {name:string}!</summary>
        public static GreetTemplate Greet => default;
        /// <summary>The <c>greet</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct GreetTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Greet"/>
            public string Template => global::MyApp.Strings.__Get("greet");
            /// <inheritdoc cref="global::MyApp.Strings.Greet"/>
            public string Render(string name) => global::MyApp.Strings.__Format("greet", ("name", name));
        }
        /// <summary>{a:int} then {b}</summary>
        public static MixTemplate Mix => default;
        /// <summary>The <c>mix</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct MixTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Mix"/>
            public string Template => global::MyApp.Strings.__Get("mix");
            /// <inheritdoc cref="global::MyApp.Strings.Mix"/>
            public string Render<T1>(int a, T1 b) => global::MyApp.Strings.__Format("mix", ("a", a), ("b", b));
        }
    }
}
