//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    public sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
            });
        }

        /// <summary>Z</summary>
        public static string Zebra => global::Dil.Loc.Get("Strings", "zebra");
        /// <summary>A</summary>
        public static string Apple => global::Dil.Loc.Get("Strings", "apple");
    }
}
