//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    public sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("en", "Dil/DilGeneratorTests/Strings.en.json"),
                ("tr", "Dil/DilGeneratorTests/Strings.tr.json"),
            }, "tr");
        }

        /// <summary>Hoşça kal</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>en</c>: Goodbye</item>
        /// <item><c>tr</c>: Hoşça kal</item>
        /// </list>
        /// </remarks>
        public static string Bye => global::Dil.Loc.Get("DilGeneratorTests/Strings", "bye");
        /// <summary>Merhaba</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>en</c>: Hello</item>
        /// <item><c>tr</c>: Merhaba</item>
        /// </list>
        /// </remarks>
        public static string Hello => global::Dil.Loc.Get("DilGeneratorTests/Strings", "hello");
    }
}
