//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("DilGeneratorTests/Strings", new (string, string)[]
            {
                ("", "Dil/DilGeneratorTests/Strings.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("DilGeneratorTests/Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("DilGeneratorTests/Strings", key, args);

        /// <summary>Cancel</summary>
        public static string Common_Cancel => global::Dil.Loc.Get("DilGeneratorTests/Strings", "Common_Cancel");
        /// <summary>Hello</summary>
        public static string hello => global::Dil.Loc.Get("DilGeneratorTests/Strings", "hello");
        /// <summary>Hello, world (dashed)</summary>
        public static string HelloWorld2 => global::Dil.Loc.Get("DilGeneratorTests/Strings", "hello-world");
        /// <summary>Hello, world</summary>
        public static string HelloWorld => global::Dil.Loc.Get("DilGeneratorTests/Strings", "HelloWorld");
        /// <summary>Two-factor</summary>
        public static string _2fa => global::Dil.Loc.Get("DilGeneratorTests/Strings", "2fa");
        /// <summary>Class</summary>
        public static string Class => global::Dil.Loc.Get("DilGeneratorTests/Strings", "class");
        /// <summary>Strings</summary>
        public static string Strings2 => global::Dil.Loc.Get("DilGeneratorTests/Strings", "Strings");
        /// <summary>Get</summary>
        public static string __Get2 => global::Dil.Loc.Get("DilGeneratorTests/Strings", "__Get");
        /// <summary>Enter the code sent to {email}</summary>
        public static Login2fa_EnterCode_EmailTemplate Login2fa_EnterCode_Email => default;
        /// <summary>The <c>Login2fa_EnterCode_Email</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct Login2fa_EnterCode_EmailTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Login2fa_EnterCode_Email"/>
            public string Template => global::MyApp.Strings.__Get("Login2fa_EnterCode_Email");
            /// <inheritdoc cref="global::MyApp.Strings.Login2fa_EnterCode_Email"/>
            public string Render<T1>(T1 email) => global::MyApp.Strings.__Format("Login2fa_EnterCode_Email", ("email", email));
        }
    }
}
