//HintName: Dil.Strings.g.cs
// <auto-generated/>
#nullable enable
namespace MyApp
{
    /// <summary>Strongly-typed localized strings, generated by Dil.</summary>
    internal sealed partial class Strings
    {
        Strings() { }

        static Strings()
        {
            global::Dil.Loc.Register("Strings", new (string, string)[]
            {
                ("", "Strings.json"),
                ("de", "Strings.de.json"),
            });
        }

        static string __Get(string key) => global::Dil.Loc.Get("Strings", key);
        static string __Format(string key, params (string Name, object? Value)[] args) =>
            global::Dil.Loc.Format("Strings", key, args);

        /// <summary>Hello</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>de</c>: Hallo</item>
        /// </list>
        /// </remarks>
        public static string Hello => global::Dil.Loc.Get("Strings", "hello");
        /// <summary>Hello, {name}!</summary>
        /// <remarks>Translations:
        /// <list type="bullet">
        /// <item><c>de</c>: Hallo, {name}!</item>
        /// </list>
        /// </remarks>
        public static GreetingTemplate Greeting => default;
        /// <summary>The <c>greeting</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct GreetingTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Greeting"/>
            public string Template => global::MyApp.Strings.__Get("greeting");
            /// <inheritdoc cref="global::MyApp.Strings.Greeting"/>
            public string Render<T1>(T1 name) => global::MyApp.Strings.__Format("greeting", ("name", name));
        }
        /// <summary>You have {count} unread messages</summary>
        public static InboxTemplate Inbox => default;
        /// <summary>The <c>inbox</c> template: <c>Template</c> is the raw value, <c>Render</c> fills in its placeholders.</summary>
        public readonly struct InboxTemplate
        {
            /// <inheritdoc cref="global::MyApp.Strings.Inbox"/>
            public string Template => global::MyApp.Strings.__Get("inbox");
            /// <inheritdoc cref="global::MyApp.Strings.Inbox"/>
            public string Render<T1>(T1 count) => global::MyApp.Strings.__Format("inbox", ("count", count));
        }
    }
}
